In [4]:
import matplotlib.pyplot as plt
import string
import numpy as np
import re
import time
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from pathlib import Path

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yinka\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
from pathlib import Path
import pandas as pd
train_path = Path('data','train.csv') 
test_path = Path('data', 'valid.csv')
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)
train_df.head(5)

ArticleId                                               Text  Category
0       1155  chancellor rallies labour voters gordon brown ...  politics
1       1980  india s maruti sees profits jump india s bigge...  business
2        386  ukip s secret weapon  by any measure  new york...  politics
3       1436  banker loses sexism claim a former executive a...  business
4        304  dallaglio eyeing lions tour place former engla...     sport

In [17]:
from sklearn.base import TransformerMixin

class text_preprocessor(TransformerMixin):
    

    def __preprocessor(text):
        
        text = text.lower() #Lowers  the text
        text = re.sub('<[^>]*>', '', text) # removes HTML Markup
        text = re.sub(r'[^a-zA-Z\s]', '', text) # removes special characters and digits
        stop_words = set(stopwords.words('english'))
        text = [word for word in text.split() if word not in stop_words and word not in string.punctuation] #removes stopwords
        text = ' '.join(word for word in text)
        return text
    
    def transform(self,df, y =None):
        
        df_copy = df.copy()
        df_copy.apply(self.__preprocessor)
        return df

In [8]:
train_sample = clean.transform(train_df[['Text']])
train_sample[0]

AttributeError: 'DataFrame' object has no attribute 'lower'

In [10]:
sample = np.arange(1.,10.)
sample

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
new = np.linspace(1.,10.)
sample == new

C:\Users\Yinka\AppData\Local\Temp\ipykernel_10420\3812521438.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  sample == new


False

In [15]:
new[:5]

array([1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388])

In [16]:
np.logspace(-4,4,20)

array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04])